[project]
name = "sequence-processing-tool"
version = "0.1.0"
description = "A simple sequence processing tool with utility scripts."
authors = [
    { name = "Yaqi Jiao" }
]
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/yaqi-jiao/Sequence_Processing_Tool_Project"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["SequenceTool"]